add_first: true
add_label_scaling: 0
arch: TextLSTM1
attack_class: 0
base_seed: 1
batch_size: 1024
checkpoint_interval: 10
dataset: trec50
dataset_labels:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 49
dataset_normalization: !!python/tuple
- !!python/tuple
    - 0
- !!python/tuple
    - 0
dataset_root: ./data/text/trec
decay_epochs: 20
decay_factor: 0.5
device_id: 0
dist_metric: MSE
distill_epochs: 1
distill_lr: 6.5
distill_steps: 1
distilled_images_per_class_per_step: 1
distributed: false
dropout: false
epochs: 210
expr_name_format: null
freeze_data: false
image_dpi: 80
init: xavier
init_labels:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 49
init_param: 1.0
input_size: 20
invert_dist: false
label_softmax: false
learnable_embedding: false
log_file: text_results/convlstm_trec50_final/distill_basic/trec50/arch(TextLSTM1,xavier,1.0)_distillLR6.5_E(210,20,0.5)_lr0.1_B1x1x1_train(known_init)/output.log
log_interval: 100
log_level: INFO
lr: 0.1
maxlen: 20
mode: distill_basic
model_dir: ./models/
model_subdir_format: null
mult_label_scaling: 1
n_nets: 1
nc: 1
ninp: 100
no_log: false
ntoken: 8000
num_classes: 50
num_distill_classes: 50
num_workers: 8
phase: train
random_init_labels: ''
reproduction_test: false
results_dir: text_results/convlstm_trec50_final
sample_n_nets: 1
source_dataset: null
start_time: '2020-04-26 20:10:18'
static_labels: 0
target_class: 1
test_batch_size: 1024
test_distill_epochs: null
test_distilled_images: loaded
test_distilled_lrs:
- loaded
test_n_nets: 1
test_n_runs: 1
test_name_format: null
test_nets_type: same_as_train
test_niter: 1
test_optimize_n_nets: 20
test_optimize_n_runs: null
textdata: true
train_nets_type: known_init
visualize: true
world_rank: 0
world_size: 1
